#!/usr/bin/env node
/**
 * Embeds the pdf.js library + worker into a generated TypeScript module so
 * the app can inline them into the extraction WebView without any network
 * access. Runs on postinstall; the output file is gitignored.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const pdfjsPackage = dirname(require.resolve('pdfjs-dist/package.json'));

/** Escape for safe inlining inside an HTML <script> block. */
function scriptSafe(source) {
  return source.replace(/<\/script/gi, '<\\/script').replace(/<!--/g, '<\\!--');
}

const pdf = readFileSync(join(pdfjsPackage, 'build/pdf.min.mjs'), 'utf8');
const worker = readFileSync(join(pdfjsPackage, 'build/pdf.worker.min.mjs'), 'utf8');
const version = JSON.parse(readFileSync(join(pdfjsPackage, 'package.json'), 'utf8')).version;

const out = `// GENERATED by scripts/embed-pdfjs.mjs — do not edit, not committed.
// pdfjs-dist ${version}
export const PDFJS_VERSION = ${JSON.stringify(version)};
export const PDFJS_SRC = ${JSON.stringify(scriptSafe(pdf))};
export const PDFJS_WORKER_SRC = ${JSON.stringify(scriptSafe(worker))};
`;

const target = join(here, '../src/pdf/pdfjsEmbedded.ts');
mkdirSync(dirname(target), { recursive: true });
writeFileSync(target, out);
console.log(`embed-pdfjs: wrote ${target} (pdfjs ${version}, ${(out.length / 1e6).toFixed(1)}MB)`);
